# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hDqCoBCqUR-J_OxFxW--psDXLJE9rtdn
"""

!pip install -q tensorflow==2.19.1 tensorflow-text==2.19.0 tf-keras==2.19.0 ml-dtypes>=0.5.0

VIDEO_URLS = {
    "naruto": [
        "https://www.youtube.com/playlist?list=PLu0W_9lII9ah7DDtYtflgwMwpT3xmjXY9"
    ],
    "luffy": [
        "https://www.youtube.com/playlist?list=PLF39633B7B03A54AE"
    ],
    "goku": [
        "https://www.youtube.com/playlist?list=PLzMcBGfZo4-nhWva-6OVh1yKWHBs4o_tR"
    ],
    "sasuke": [
        "https://www.youtube.com/watch?v=M5QasY3Lyyg"
    ],
    "hinata": [
        "https://www.youtube.com/watch?v=NjzlU5h8gJQ"
    ],
    "ichigo": [
        "https://www.youtube.com/playlist?list=PLp2TZ8bu0hk0Yt2kDJt5p84upkB7E9xFJ"
    ],
    "levi": [
        "https://www.youtube.com/watch?v=4iLm1cLoT6Q"
    ],
    "tanjiro": [
        "https://www.youtube.com/playlist?list=PL6v8kaquC0seQ9m2nTZy0_xZ8KEJh5mW5"
    ],
    "gojo": [
        "https://www.youtube.com/watch?v=g1F_ZNIxDq8"
    ],
    "zoro": [
        "https://www.youtube.com/watch?v=BvC8aI_vuH4"
    ]
}

!ls /content
!ls /content/anime_dataset_raw

import os, shutil

DATASET_ROOT = "/content/anime_dataset_raw"
os.makedirs(DATASET_ROOT, exist_ok=True)

for cls in ["goku","naruto","luffy","sasuke","hinata","ichigo","levi","tanjiro","gojo","zoro"]:
    shutil.move(f"/content/{cls}", f"{DATASET_ROOT}/{cls}")

print(os.listdir(DATASET_ROOT))

import os, shutil
from sklearn.model_selection import train_test_split

RAW_DIR = "/content/anime_dataset_raw"
OUT_DIR = "/content/dataset_split"

for split in ["train", "val", "test"]:
    os.makedirs(os.path.join(OUT_DIR, split), exist_ok=True)

for cls in os.listdir(RAW_DIR):
    files = [f for f in os.listdir(os.path.join(RAW_DIR, cls))
             if f.lower().endswith(('.jpg','.png','.jpeg'))]

    train, temp = train_test_split(files, test_size=0.3, random_state=42)
    val, test = train_test_split(temp, test_size=0.5, random_state=42)

    for split_name, split_files in zip(["train","val","test"], [train,val,test]):
        dst = os.path.join(OUT_DIR, split_name, cls)
        os.makedirs(dst, exist_ok=True)
        for f in split_files:
            shutil.copy(os.path.join(RAW_DIR,cls,f), os.path.join(dst,f))

print("✅ Dataset split complete")

import tensorflow as tf

IMG_SIZE = (300,300)
BATCH_SIZE = 32

train_ds = tf.keras.utils.image_dataset_from_directory(
    "/content/dataset_split/train",
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    label_mode="categorical",
    shuffle=True
)

val_ds = tf.keras.utils.image_dataset_from_directory(
    "/content/dataset_split/val",
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    label_mode="categorical",
    shuffle=False
)

test_ds = tf.keras.utils.image_dataset_from_directory(
    "/content/dataset_split/test",
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    label_mode="categorical",
    shuffle=False
)

class_names = train_ds.class_names
NUM_CLASSES = len(class_names)
print("Classes:", class_names)

AUTOTUNE = tf.data.AUTOTUNE
train_ds = train_ds.prefetch(AUTOTUNE)
val_ds = val_ds.prefetch(AUTOTUNE)
test_ds = test_ds.prefetch(AUTOTUNE)

from tensorflow.keras import layers

data_augmentation = tf.keras.Sequential([
    layers.RandomFlip("horizontal"),
    layers.RandomRotation(0.15),
    layers.RandomZoom(0.2),
    layers.RandomContrast(0.2),
])

from tensorflow.keras.applications import EfficientNetB3
from tensorflow.keras.layers import Dense, Dropout, GlobalAveragePooling2D
from tensorflow.keras.models import Model

base_model = EfficientNetB3(
    include_top=False,
    weights="imagenet",
    input_shape=(300,300,3)
)
base_model.trainable = False

inputs = tf.keras.Input(shape=(300,300,3))
x = data_augmentation(inputs)
x = tf.keras.applications.efficientnet.preprocess_input(x)
x = base_model(x, training=False)
x = GlobalAveragePooling2D()(x)
x = Dense(512, activation="relu")(x)
x = Dropout(0.5)(x)
outputs = Dense(NUM_CLASSES, activation="softmax")(x)

model = Model(inputs, outputs)

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=3e-4),
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)

model.summary()

EPOCHS = 15

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=EPOCHS
)

base_model.trainable = True
for layer in base_model.layers[:-40]:
    layer.trainable = False

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-5),
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)

history_finetune = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=10
)

test_loss, test_acc = model.evaluate(test_ds)
print("✅ Test accuracy:", test_acc)

model.save("anime_character_classifier.h5")
print("✅ Model saved as anime_character_classifier.h5")

